In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("D:\Tahir\IBM all Lab\Machine learning\hiring.csv")

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    NaN                           7      72000   
7     eleven                    7.0                           8      80000   

   Unnamed: 4  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN

### Data cleaning process

In [4]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)', 'Unnamed: 4'],
      dtype='object')

In [5]:
df.drop(['Unnamed: 4'],axis=1,inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
!pip install word2number

In [7]:
from word2number import w2n

In [8]:
df.experience = df.experience.fillna('zero')  # fill na value with zero in experiece column

In [9]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df["experience"] = df.experience.astype(str)
df.experience = df.experience.apply(w2n.word_to_num)  # converting word 2 num 
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [11]:
mean = df['test_score(out of 10)'].mean()
mean

7.857142857142857

In [12]:
import math
mean = math.floor(mean)
mean

7

In [13]:

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean)  # fillin na value in test score with mean value 
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']],df[['salary($)']])

LinearRegression()

In [15]:
reg.coef_    # these are the coeficient 

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [16]:
reg.intercept_ # intercept

array([14992.65144669])

In [17]:
# salary for the candidates 
# 1- experience 2 years , test score 9, interview score 6
# 2- experience 12 years , test score 10, interview score 10

In [18]:
reg.predict([[2,9,6]])

C:\Users\mdtah\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [19]:
reg.predict([[12,10,10]])

C:\Users\mdtah\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])